#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Anupam Sharma

# Short bio or description (displayed in the header)
description: I am a highly skilled software development engineer with a keen interest in machine learning, software development, motion planning, navigation, and SLAM. With over 5 years of experience, I excel in the entire software development lifecycle, from concept to deployment. I am known for leading projects, mentoring teams, and fostering cross-functional collaboration. Proficient in multiple programming languages, including Python, C++, and Java, I deliver high-quality software on time and within budget. In addition to my programming skills, I have expertise in key technologies such as PyTorch, TensorFlow, ROS (Robot Operating System), Matplotlib, Pandas, Ray, and Optuna. This technical proficiency empowers me to tackle complex challenges and implement cutting-edge solutions effectively. Currently pursuing a Master's in Robotics at the State University of New York at Buffalo, my focus lies in robotics, machine learning, and AI. I started my career at Akamai as a new hire and climbed to the position of senior Software Development Engineer in five years, gaining expertise in Content Delivery Networks (CDN). My insatiable curiosity drives me to seek new challenges and stay ahead in the ever-evolving field of software development. I look forward to pushing the boundaries of technology in the exciting times ahead. GitHub- https://github.com/anupam-sharma-1

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/13178379?s=400&u=4b7780760c73a499d74680956269dd86921519e9&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: anupamsh@buffalo.edu
  github: https://github.com/anupam-sharma-1
  linkedin: https://www.linkedin.com/in/anupamsharma5/



# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "https://anupam-sharma-1.github.io/index/resume"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
